/**
 * Hex map geometry and the board data format (generated by packages/data
 * scripts/boards.ts from fhtts). Axial coordinates (x, y) with pointy-top
 * hexes; y points up-right as in the scenario book:
 *   screen x = size * (x + y / 2), screen y = -size * sqrt(3) / 2 * y
 * where size is the distance between neighbouring hex centres.
 */
import type { Hex } from './state';

export type { Hex };

export interface BoardTrigger {
  type?: string;
  action?: string;
  what?: { type?: string; name?: string };
  id?: string;
}

export interface BoardTile {
  name: string;
  /** Counter-clockwise degrees, multiple of 60. */
  orientation: number;
  origin: Hex;
  image?: {
    path: string;
    width: number;
    height: number;
    /** Image px between neighbouring hex centres. */
    spacing: number;
    /** Image px of the tile's origin hex. */
    origin: { x: number; y: number };
    /** Extra counter-clockwise degrees to bring the image into the tile's frame. */
    rotation: number;
  };
}

export type BoardItem =
  | { kind: 'monster'; name: string; label: string; hex: Hex; levels: string; standee?: number }
  | { kind: 'token'; name: string; hex: Hex; trigger?: BoardTrigger }
  | { kind: 'overlay'; name: string; type: string; hexes: Hex[]; orientation: number; trigger?: BoardTrigger; image?: string };

export interface BoardMap {
  /** 'scenario', 'section', 'section.solo', 'choice'. */
  type: string;
  /** Scenario book page (for 'scenario') or section number. */
  name: string;
  tiles: string[];
  items: BoardItem[];
}

export interface BoardFile {
  scenario: string;
  tiles: BoardTile[];
  maps: BoardMap[];
}

export const SQRT3 = Math.sqrt(3);

export function hexToPixel(h: Hex, size: number): { x: number; y: number } {
  return { x: size * (h.x + h.y / 2), y: (-size * SQRT3 * h.y) / 2 };
}

/** Nearest hex to a screen point (cube rounding). */
export function pixelToHex(p: { x: number; y: number }, size: number): Hex {
  const y = (-2 * p.y) / (SQRT3 * size);
  const x = p.x / size - y / 2;
  const z = -x - y;
  let rx = Math.round(x);
  let ry = Math.round(y);
  const rz = Math.round(z);
  const dx = Math.abs(rx - x);
  const dy = Math.abs(ry - y);
  const dz = Math.abs(rz - z);
  if (dx > dy && dx > dz) rx = -ry - rz;
  else if (dy > dz) ry = -rx - rz;
  return { x: rx + 0, y: ry + 0 };
}

export function hexDistance(a: Hex, b: Hex): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return (Math.abs(dx) + Math.abs(dy) + Math.abs(dx + dy)) / 2;
}

/** Corner points of a hex, for SVG polygons. */
export function hexCorners(h: Hex, size: number, scale = 1): string {
  const c = hexToPixel(h, size);
  const r = (size / SQRT3) * scale;
  return Array.from({ length: 6 }, (_, k) => {
    const a = ((30 + 60 * k) * Math.PI) / 180;
    return `${(c.x + r * Math.cos(a)).toFixed(1)},${(c.y + r * Math.sin(a)).toFixed(1)}`;
  }).join(' ');
}

export const hexKey = (h: Hex) => `${h.x},${h.y}`;
